# when the tool executable is run with no arguments and this file is present
# in the same directory as the executable, this file will be used to describe
# which version of Python to run, how to load it, and which Python script to run.
#
# the python section should contain:
#   home: a path pointing to the Python home directory, typically relative to the tool executable
#   library_name: the Python library within the home directory.
#   paths: paths to add to the Python sys.path before launching.
#
# the app section should contain:
#   identifier: the package identifier of the application. in this case, Nion Swift

[python]
home = "."
library_name = "python310.dll"
paths = ["lib", "DLLS", "python-nionswift/lib/site-packages"]

[app]
identifier = "nionui_app.nionswift"
